export type Guia = {
  id: string;
  ownerUid: string;
  nome: string;
  descricao?: string;
  tipo: string;
  cidades?: string[];
  cidadeIds: string[];
  cidadeNomes?: string[];
  foto_perfil?: string;
  imagemUrl?: string;
  endereco?: string;
  codigoIdentificacao?: string;
  especializacao?: string;
  idiomas?: string[];
  experiencia?: string;
  valor?: string;
  tipoCobranca?: 'pessoa' | 'grupo';
  telefone?: string;
  status?: 'pendente' | 'aprovado' | 'rejeitado';
};
